# Generated by Django 4.1.3 on 2023-11-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('pontos', models.IntegerField(default=0)),
                ('saldo', models.FloatField(default=0.0)),
            ],
        ),
    ]
